export interface Parcels {
    parcelId: number; // Primary Key
    trackingCode: string; // Tracking Code (nvarchar)
    senderName: string | null; // Sender Name (varchar)
    senderPhone: number | null; // Sender Phone (int, nullable)
    senderAddress: string | null; // Sender Address (varchar, nullable)
    senderAlternativetoAddress: string | null; // Sender Alternative Address (varchar, nullable)
    receiverName: string | null; // Receiver Name (varchar, nullable)
    receiverPhone: number | null; // Receiver Phone (int, nullable)
    receiverEmail: string | null; // Receiver Email (varchar, nullable)
    receiverAddress: string | null; // Receiver Address (varchar, nullable)
    receiverAlternativetoAddress: string | null; // Receiver Alternative Address (varchar, nullable)
    senderCustomerId: number | null; // Sender Customer ID (int, nullable)
    sendTime: Date | null; // Parcel Send Time (datetime, nullable)
    receiverCustomerId: number | null; // Receiver Customer ID (int, nullable)
    receiveTime: Date | null; // Parcel Receive Time (datetime, nullable)
    senderBranchId: number | null; // Sender Branch ID (int, nullable)
    receiverBranchId: number | null; // Receiver Branch ID (int, nullable)
    estimatedReceiveTime: Date | null; // Estimated Receive Time (datetime, nullable)
    isPaid: boolean | false; // Payment Status (bit, nullable)
    price: number | null; // Parcel Price (decimal, nullable)
    weight: number | null; // Parcel Weight (float, nullable)
    createdBy: string | null; // Created By (nvarchar, nullable)
    createDate: Date | null; // Create Date (datetime, nullable)
    updatedBy: string | null; // Updated By (nvarchar, nullable)
    updateDate: Date | null; // Update Date (datetime, nullable)
    sendingBranch: boolean | null; // Sending Branch Status (bit, nullable)
    percelSendingDestribution: boolean | null; // Distribution Status during Sending (bit, nullable)
    recebingDistributin: boolean | null; // Distribution Status during Receiving (bit, nullable)
    recebingBranch: boolean | null; // Receiving Branch Status (bit, nullable)
    recebingReceber: boolean | null; // Receiving Receiver Status (bit, nullable)
    isActive: boolean | null; // Active Status (bit, nullable)
    vanId: number | null; // Van ID (int, nullable)
    driverId: number | null; // Driver ID (int, nullable)
    deliveryChargeId: number | null; // Delivery Charge ID (int, nullable)
    parcelTypeId: number | null; // Parcel Type ID (int, nullable)
    status:string|null;
  }